# Calculates the number of distinct terms in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100

set = set()
for a in range(2,101):
	for b in range(2,101):
		set.add(a**b)
print(len(set))
