# Calculates the number of distinct terms in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100

array = []

for a in range(2,101):
	for b in range(2,101):
		if a**b not in array:
			array.append(a**b)
print(len(array))